{% set name = "flake8-markdown" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ec2aa584edb16a7ad5a5e9ea59c287aebddd9cb92ebcb5b10efa1402e52caf1e

build:
  number: 0
  noarch: python
  entry_points:
    - flake8-markdown = flake8_markdown:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=1.0.0
    - python >=3.7
  run:
    - flake8 >=5.0
    - python >=3.7

test:
  imports:
    - flake8_markdown
  commands:
    - pip check
    - flake8-markdown --help
  requires:
    - pip

about:
  home: https://github.com/johnfraney/flake8-markdown
  summary: Lints Python code blocks in Markdown files using flake8
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
