{% set name = "flake8-markdown" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 69d2a3d650ad6e995885c46c96963939eb28bd08f1832714ad09717b58848059

build:
  number: 0
  noarch: python
  entry_points:
    - flake8-markdown = flake8_markdown:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=1.1.0
    - poetry-core
    - python {{ python_min }}
  run:
    - flake8 >=5.0.0
    - python >={{ python_min }}

test:
  imports:
    - flake8_markdown
  commands:
    - pip check
    - flake8-markdown --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/johnfraney/flake8-markdown
  summary: Lints Python code blocks in Markdown files using flake8
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
